### ISSUE TITLE
direct access of $_GET/$_POST is not allowed.

### ISSUE THREAD

**Issue by purnendudash** [abautu/moodle-repository_dropzone#1]
https://github.com/abautu/moodle-repository_dropzone/blob/abb8443df443a7ae6de41b21ca95eb81a591e1c9/lib.php#L72

The same was being used a lot in your upload.php file too.

Kindly directly use $_POST / $_FILES etc. 

Please replace these with optional/required_param calls with appropriate formats such as PARAM_INT, etc. Kindly check this for your reference - https://moodledev.io/general/development/policies/security#dont-trust-any-input-from-users

**Comment by abautu** [comment]
I replaced $_POST with optional_param/required_param. However, for $_FILES, I am leaving it as it is because a) I didn't find any useful functions for it, b) upload repository in Moodle core does the same.

**Comment by danmarsden** [comment]
nice to see PARAM_ALPHANUMEXT used in your new code there too - that should prevent a directory traversal attack as it doesn't allow dots.  - imagine if the $elementname contained something like "../../config.php" - or other alternatives which could cause problems..

**Comment by abautu** [comment]
> nice to see PARAM_ALPHANUMEXT used in your new code there too - that should prevent a directory traversal attack as it doesn't allow dots. - imagine if the $elementname contained something like "../../config.php" - or other alternatives which could cause problems..

It was already validated by https://github.com/abautu/moodle-repository_dropzone/commit/51b43bc6a23195941a11c3041f581b7e03c4a05a#diff-8f5ff72ef1cf59199cfc4bbf16f2475d09e448601242f0d2c51bb94bd4aa1395L57 , but I agree required_param(... PARAM_ALPHANUMEXT) looks better :+1:
