### ISSUE TITLE
Not sure about this inclusion?

### ISSUE THREAD

**Issue by purnendudash** [abautu/moodle-repository_dropzone#2]
https://github.com/abautu/moodle-repository_dropzone/blob/abb8443df443a7ae6de41b21ca95eb81a591e1c9/upload.php#L3C15-L3C40

Could you please explain, why this was being included as hardcoded string.

**Comment by mudrd8mz** [comment]
Well spotted, this is a clear functionality blocker.

**Comment by abautu** [comment]
Good catch. Left overs from some dev testing.
