### ISSUE TITLE
Kindly use file API insead

### ISSUE THREAD

**Issue by purnendudash** [abautu/moodle-repository_dropzone#4]
This may be a bit risky while using command like "mkdir", would recommended to use the File API.

Reference as follows - https://moodledev.io/docs/apis/subsystems/files

https://github.com/abautu/moodle-repository_dropzone/blob/abb8443df443a7ae6de41b21ca95eb81a591e1c9/upload.php#L54

**Comment by abautu** [comment]
Hi. Thank you for the suggestion, but I believe FileAPI is not appropriate in this context (the upload file is stored in temporary file just at the AJAX record, while the FileAPI will be used to move it to proper storage when upload method is called).

However, I replaced the hardcoded 0700 permissions with $CFG->directorypermissions, to be consistent with the usage of mkdir in FileSystem repository plugin (and other places from Moodle core).
