### ISSUE TITLE
css should be included Bia styles.css

### ISSUE THREAD

**Issue by purnendudash** [abautu/moodle-repository_dropzone#6]
Kindly check this for reference 

https://moodledev.io/general/community/plugincontribution/checklist#css-styles

https://github.com/abautu/moodle-repository_dropzone/blob/abb8443df443a7ae6de41b21ca95eb81a591e1c9/css/dropzone.css#L1

**Comment by abautu** [comment]
dropzone.css and dropzone.min.css are the default CSS classes that come with Dropzone (e.g. they are needed for dropzone animation to work). They are added in the iframed upload page (using embeded page layout) here https://github.com/abautu/moodle-repository_dropzone/blob/main/upload.php#L79 

I do not plan to edit them, but I don't want them to be included on each Moodle page either, therefore I did not named these files style.css.
